[package]
name = "rist-tools"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false
description = "Operational qualification tools for rist-rs"

[dependencies]
rist-core = { version = "0.1.0", path = "../rist-core" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[dev-dependencies]
rist-mio = { version = "0.1.0", path = "../rist-mio" }
