//! Raw FFI bindings to librist.
//!
//! This crate provides low-level bindings generated by bindgen.
//! For a safe API, use the `rist` crate instead.

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(clippy::all)]

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
